version: "3.8"
services:
  kafka:
    image: bitnami/kafka:3.7
    environment:
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      - app-network
  emote-generator:
    build: ./emote-generator
    depends_on:
      - kafka
    networks:
      - app-network
  server-b:
    build: ./server-b
    depends_on:
      - kafka
    networks:
      - app-network
  server-a:
    build: ./server-a
    depends_on:
      - kafka
    networks:
      - app-network
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - server-a
      - server-b
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
